django.template.exceptions.TemplateSyntaxError: default requires 2 arguments, 1 provided; celery.beat.SchedulingError: Couldn't apply scheduled task delayed-security-sync-task: synch_guardian() takes 0 positional arguments but 1 was given